### ISSUE TITLE
Installation issues

### ISSUE THREAD

**Issue by rdrighetto** [MLI-lab/DeepDeWedge#1]
Hi,

I just wanted to share that following the instructions provided for installation did not work for me. Here is how I got to install `DeepDeWedge`:

First, the required Python version was not specified anywhere. After some trial and error (regarding the `pytorch` dependency and such) I found that `python=3.10` works on my system (CentOS 7, NVIDIA driver 545.23.08, CUDA 12.3)

```
git clone https://github.com/MLI-lab/DeepDeWedge
cd DeepDeWedge
mamba create -n DeepDeWedge_env python=3.10
```

Then I had to edit the `requirements.txt` to be as follows:
```
torch==1.12.1
mrcfile
matplotlib
pandas
pytorch-lightning==1.8.0.post1
scikit-image
```
and then
```
pip install -r requirements.txt`
```
finally worked.

Hope this helps other people out there!

Thank you,
Ricardo

**Comment by SimWdm** [comment]
Hello Ricardo,

Thanks for trying our method and for opening this issue! I apologize for your trouble with the installation because I did not specify the requirements correctly. I will update the installation instructions and the requirements.

Best,
Simon
