### ISSUE TITLE
Installing DeepDeWedge using standard instructions will fail due to pip 24.2 being installed 

### ISSUE THREAD

**Issue by DcShepherd** [MLI-lab/DeepDeWedge#11]
Hello,

When installing DeepDeWedge using the instructions pip==24.2 will be installed

This causes a problem because installing pytorch lightning versions below 1.8.4  will fail with pip versions >23.2.1
See: [pipx/issues/988](https://github.com/pypa/pipx/issues/998)

It throws the error

```
Downloading pytorch_lightning-1.8.1-py3-none-any.whl.metadata (25 kB)
WARNING: Ignoring version 1.8.1 of pytorch-lightning since it has invalid metadata:
Requested pytorch-lightning==1.8.1 from https://files.pythonhosted.org/packages/54/8f/ff9e74724d1c203e8f1efe4b763ef941a68672eaeae9512391a5d3125cae/pytorch_lightning-1.8.1-py3-none-any.whl (from -r requirements.txt (line 5)) has invalid metadata: .* suffix can only be used with `==` or `!=` operators
    torch (>=1.9.*)
           ~~~~~~^
Please use pip<24.1 if you need to use this version.
```

To get around this one has to run ```pip install pip==23.2.1``` in the conda environment  before running ```pip install -r requirements.txt```

**Comment by SimWdm** [comment]
Thank you for pointing that out! 🙏🏼 🙂 

I could reproduce the error and can also confirm that your fix of downgrading pip works.

Before I make the corresponding changes in the installation instructions, I want to make sure that downgrading pip does not cause any issues further down the road. I think as long as all dependencies are installed with the correct versions, the change should be save. What is your thought on that?

**Comment by DcShepherd** [comment]
Hi Simon,

I was also thinking if downgrading would cause any problems later and I tried to find a more "elegant" solution to resolve the dependency but I came up with nothing. 

From what I have gathered because "1.8.0.post1" is a non-standard version specifier any pip version >23.2.1 will not recognise the format. The format that post releases are supposed to follow is X.Y.postN. I was going to check to see from which version lightning started using the correct syntax but I got sidetracked with fixing nvidia drivers and forgot 😅.

[See #12063](https://github.com/pypa/pip/issues/12063)

What that being said, every fix for anything related to this issue has been to downgrade the pip  to version to 23.2.1

**Comment by SimWdm** [comment]
Thanks again, Doulin, for your input! 🙏🏼 
I have updated the installation instructions according to your proposed fix. Now the conda env is created with pip 23.3.1. I also had to add 2 new dependencies to the requirements.txt because another pip error-related occurred, but now it should be fine.
