### ISSUE TITLE
prepare-data does not overwrite previous run folders

### ISSUE THREAD

**Issue by Mishaczech** [MLI-lab/DeepDeWedge#3]
Hi,
it is a bit of a pain to erase all folders in subtomo-dir every time the run crashes and I want to re-run the fixed command. I am sure this is an easy fix.

**Comment by Mishaczech** [comment]
Running the second command returns this error. I am not clear on what is happening there.

Command: ddw fit-model --unet-params-dict chans 32 drop_prob 0.0 num_downsample_layers 2^C-adam-params-dict lr 0.0004 --num-epochs 100 --batch-size 5 --subtomo-size 50 --mw-angle 60 --gpu 0 --num-workers 3

Error:
Traceback (most recent call last) ────────────────────────────────╮
│ /cemcofsw/em/deepDeWedge/240507/bin/ddw:8 in <module>                                            │
│                                                                                                  │
│   5 from ddw.app import main                                                                     │
│   6 if __name__ == '__main__':                                                                   │
│   7 │   sys.argv[0] = re.sub(r'(-script\.pyw|\.exe)?$', '', sys.argv[0])                         │
│ ❱ 8 │   sys.exit(main())                                                                         │
│   9                                                                                              │
│                                                                                                  │
│ ╭───────────────────────────────────── locals ─────────────────────────────────────╮             │
│ │ main = <function main at 0x7f4db165f0a0>                                         │             │
│ │   re = <module 're' from '/cemcofsw/em/deepDeWedge/240507/lib/python3.10/re.py'> │             │
│ │  sys = <module 'sys' (built-in)>                                                 │             │
│ ╰──────────────────────────────────────────────────────────────────────────────────╯             │
│                                                                                                  │
│ /cemcofsw/em/deepDeWedge/240507/lib/python3.10/site-packages/ddw/app.py:14 in main               │
│                                                                                                  │
│   11                                                                                             │
│   12                                                                                             │
│   13 def main():                                                                                 │
│ ❱ 14 │   app()                                                                                   │
│   15                                                                                             │
│   16                                                                                             │
│   17 if __name__ == "__main__":                                                                  │
│                                                                                                  │
│ /cemcofsw/em/deepDeWedge/240507/lib/python3.10/site-packages/typer/main.py:326 in __call__       │
│                                                                                                  │
│ /cemcofsw/em/deepDeWedge/240507/lib/python3.10/site-packages/typer/main.py:309 in __call__       │
│                                                                                                  │
│ /cemcofsw/em/deepDeWedge/240507/lib/python3.10/site-packages/click/core.py:1157 in __call__      │
│                                                                                                  │
│ /cemcofsw/em/deepDeWedge/240507/lib/python3.10/site-packages/typer/core.py:723 in main           │
│                                                                                                  │
│ /cemcofsw/em/deepDeWedge/240507/lib/python3.10/site-packages/typer/core.py:193 in _main          │
│                                                                                                  │
│ /cemcofsw/em/deepDeWedge/240507/lib/python3.10/site-packages/click/core.py:1686 in invoke        │
│                                                                                                  │
│ /cemcofsw/em/deepDeWedge/240507/lib/python3.10/site-packages/click/core.py:943 in make_context   │
│                                                                                                  │
│ /cemcofsw/em/deepDeWedge/240507/lib/python3.10/site-packages/click/core.py:1408 in parse_args    │
│                                                                                                  │
│ /cemcofsw/em/deepDeWedge/240507/lib/python3.10/site-packages/click/core.py:2400 in               │
│ handle_parse_result                                                                              │
│                                                                                                  │
│ /cemcofsw/em/deepDeWedge/240507/lib/python3.10/site-packages/click/core.py:2362 in process_value │
│                                                                                                  │
│ /cemcofsw/em/deepDeWedge/240507/lib/python3.10/site-packages/typer/main.py:1001 in wrapper       │
│                                                                                                  │
│ /cemcofsw/em/deepDeWedge/240507/lib/python3.10/ast.py:110 in literal_eval                        │
│                                                                                                  │
│    107 │   │   │   │   else:                                                                     │
│    108 │   │   │   │   │   return left - right                                                   │
│    109 │   │   return _convert_signed_num(node)                                                  │
│ ❱  110 │   return _convert(node_or_string)                                                       │
│    111                                                                                           │
│    112                                                                                           │
│    113 def dump(node, annotate_fields=True, include_attributes=False, *, indent=None):           │
│                                                                                                  │
│ ╭─────────────────────────────────────────── locals ───────────────────────────────────────────╮ │
│ │              _convert = <function literal_eval.<locals>._convert at 0x7f4c4099a680>          │ │
│ │          _convert_num = <function literal_eval.<locals>._convert_num at 0x7f4c4099a560>      │ │
│ │   _convert_signed_num = <function literal_eval.<locals>._convert_signed_num at               │ │
│ │                         0x7f4c4099a5f0>                                                      │ │
│ │ _raise_malformed_node = <function literal_eval.<locals>._raise_malformed_node at             │ │
│ │                         0x7f4c4099a440>                                                      │ │
│ │        node_or_string = <ast.Name object at 0x7f4c409b4850>                                  │ │
│ ╰──────────────────────────────────────────────────────────────────────────────────────────────╯ │
│                                                                                                  │
│ /cemcofsw/em/deepDeWedge/240507/lib/python3.10/ast.py:109 in _convert                            │
│                                                                                                  │
│    106 │   │   │   │   │   return left + right                                                   │
│    107 │   │   │   │   else:                                                                     │
│    108 │   │   │   │   │   return left - right                                                   │
│ ❱  109 │   │   return _convert_signed_num(node)                                                  │
│    110 │   return _convert(node_or_string)                                                       │
│    111                                                                                           │
│    112                                                                                           │
│                                                                                                  │
│ ╭─────────────────────────────────────────── locals ───────────────────────────────────────────╮ │
│ │              _convert = <function literal_eval.<locals>._convert at 0x7f4c4099a680>          │ │
│ │          _convert_num = <function literal_eval.<locals>._convert_num at 0x7f4c4099a560>      │ │
│ │   _convert_signed_num = <function literal_eval.<locals>._convert_signed_num at               │ │
│ │                         0x7f4c4099a5f0>                                                      │ │
│ │ _raise_malformed_node = <function literal_eval.<locals>._raise_malformed_node at             │ │
│ │                         0x7f4c4099a440>                                                      │ │
│ │                  node = <ast.Name object at 0x7f4c409b4850>                                  │ │
│ ╰──────────────────────────────────────────────────────────────────────────────────────────────╯ │
│                                                                                                  │
│ /cemcofsw/em/deepDeWedge/240507/lib/python3.10/ast.py:83 in _convert_signed_num                  │
│                                                                                                  │
│     80 │   │   │   │   return + operand                                                          │
│     81 │   │   │   else:                                                                         │
│     82 │   │   │   │   return - operand                                                          │
│ ❱   83 │   │   return _convert_num(node)                                                         │
│     84 │   def _convert(node):                                                                   │
│     85 │   │   if isinstance(node, Constant):                                                    │
│     86 │   │   │   return node.value                                                             │
│                                                                                                  │
│ ╭──────────────────────────────────── locals ────────────────────────────────────╮               │
│ │ _convert_num = <function literal_eval.<locals>._convert_num at 0x7f4c4099a560> │               │
│ │         node = <ast.Name object at 0x7f4c409b4850>                             │               │
│ ╰────────────────────────────────────────────────────────────────────────────────╯               │
│                                                                                                  │
│ /cemcofsw/em/deepDeWedge/240507/lib/python3.10/ast.py:74 in _convert_num                         │
│                                                                                                  │
│     71 │   │   raise ValueError(msg + f': {node!r}')                                             │
│     72 │   def _convert_num(node):                                                               │
│     73 │   │   if not isinstance(node, Constant) or type(node.value) not in (int, float, comple  │
│ ❱   74 │   │   │   _raise_malformed_node(node)                                                   │
│     75 │   │   return node.value                                                                 │
│     76 │   def _convert_signed_num(node):                                                        │
│     77 │   │   if isinstance(node, UnaryOp) and isinstance(node.op, (UAdd, USub)):               │
│                                                                                                  │
│ ╭─────────────────────────────────────────── locals ───────────────────────────────────────────╮ │
│ │ _raise_malformed_node = <function literal_eval.<locals>._raise_malformed_node at             │ │
│ │                         0x7f4c4099a440>                                                      │ │
│ │                  node = <ast.Name object at 0x7f4c409b4850>                                  │ │
│ ╰──────────────────────────────────────────────────────────────────────────────────────────────╯ │
│                                                                                                  │
│ /cemcofsw/em/deepDeWedge/240507/lib/python3.10/ast.py:71 in _raise_malformed_node                │
│                                                                                                  │
│     68 │   │   msg = "malformed node or string"                                                  │
│     69 │   │   if lno := getattr(node, 'lineno', None):                                          │
│     70 │   │   │   msg += f' on line {lno}'                                                      │
│ ❱   71 │   │   raise ValueError(msg + f': {node!r}')                                             │
│     72 │   def _convert_num(node):                                                               │
│     73 │   │   if not isinstance(node, Constant) or type(node.value) not in (int, float, comple  │
│     74 │   │   │   _raise_malformed_node(node)                                                   │
│                                                                                                  │
│ ╭────────────────── locals ───────────────────╮                                                  │
│ │  lno = 1                                    │                                                  │
│ │  msg = 'malformed node or string on line 1' │                                                  │
│ │ node = <ast.Name object at 0x7f4c409b4850>  │                                                  │
│ ╰─────────────────────────────────────────────╯

**Comment by SimWdm** [comment]
Thanks for using DeepDeWedge and for opening these two issues!
Unfortunately, I am out of office for the remainder of this week, but I will get back to you at the beginning of next week.

Best,
Simon
