### ISSUE TITLE
ddw refine-tomogram overwrite error

### ISSUE THREAD

**Issue by wlugmayr** [MLI-lab/DeepDeWedge#5]
I installed the software yesterday (after implemented overwrite in prepare_data comment) and i got the following error in the tutorial run (provided config with updated : model_checkpoint_file: "./tutorial_project/logs/version_3/checkpoints/epoch/epoch=999.ckpt")

ddw refine-tomogram --config ./config.yaml

[ddw_refine.log](https://github.com/MLI-lab/DeepDeWedge/files/15307745/ddw_refine.log)

**Comment by SimWdm** [comment]
Thank you for using DeepDeWedge and for opening this issue! 
I apologise for the bug I introduced with my last commit. I have just pushed a fix. Please let me know if it solved your issue.

Best,
Simon

**Comment by wlugmayr** [comment]
Thanks for the quick fix. It seems to run now:

Computing model-input normalization statistics: 100%|██████████| 26/26 [00:49<00:00,  1.91s/it]
Refining tomo0: 100%|██████████| 54/54 [00:18<00:00,  2.90it/s]
Refining tomo1: 100%|██████████| 54/54 [00:18<00:00,  2.91it/s]
Saving refined tomogram to tutorial_project/refined_tomograms/tomo_even_frames+tomo_odd_frames_refined.rec

cheers,
wolfgang

**Comment by SimWdm** [comment]
Great news! If you ever have any other problems with the software or any questions, please don't hesitate to contact me or open another issue.

Best,
Simon
